title = "gitleaks config"

## Cryptographic keys
[[rules]]
id = "PKCS8-PK"
description = "PKCS8 private key"
regex = '''-----BEGIN PRIVATE KEY-----'''

[[rules]]
id = "RSA-PK"
description = "RSA private key"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''

[[rules]]
id = "OPENSSH-PK"
description = "SSH private key"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''

[[rules]]
id = "PGP-PK"
description = "PGP private key"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''

[[rules]]
id = "github-pat"
description = "Github Personal Access Token"
regex = '''ghp_[0-9a-zA-Z]{36}'''

[[rules]]
id = "github-oauth"
description = "Github OAuth Access Token"
regex = '''gho_[0-9a-zA-Z]{36}'''

[[rules]]
id = "SSH-DSA-PK"
description = "SSH (DSA) private key"
regex = '''-----BEGIN DSA PRIVATE KEY-----'''

[[rules]]
id = "SSH-EC-PK"
description = "SSH (EC) private key"
regex = '''-----BEGIN EC PRIVATE KEY-----'''

## API TOKENS
[[rules]]
id = "gitlab-pat"
description = "GitLab Personal Access Token"
regex = '''glpat-[0-9a-zA-Z\-]{20}'''

[[rules]]
id = "aws-access-token"
description = "AWS"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''

[[rules]]
id = "github-app-token"
description = "Github App Token"
regex = '''(ghu|ghs)_[0-9a-zA-Z]{36}'''

[[rules]]
id = "github-refresh-token"
description = "Github Refresh Token"
regex = '''ghr_[0-9a-zA-Z]{76}'''

[[rules]]
id = "shopify-shared-secret"
description = "Shopify shared secret"
regex = '''shpss_[a-fA-F0-9]{32}'''

[[rules]]
id = "shopify-access-token"
description = "Shopify access token"
regex = '''shpat_[a-fA-F0-9]{32}'''

[[rules]]
id = "shopify-custom-access-token"
description = "Shopify custom app access token"
regex = '''shpca_[a-fA-F0-9]{32}'''

[[rules]]
id = "shopify-private-app-access-token"
description = "Shopify private app access token"
regex = '''shppa_[a-fA-F0-9]{32}'''

[[rules]]
id = "slack-access-token"
description = "Slack token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''

[[rules]]
id = "stripe-access-token"
description = "Stripe"
regex = '''(?i)(sk|pk)_(test|live)_[0-9a-z]{10,32}'''

[[rules]]
id = "pypi-upload-token"
description = "PyPI upload token"
regex = '''pypi-AgEIcHlwaS5vcmc[A-Za-z0-9-_]{50,1000}'''

[[rules]]
id = "gcp-service-account"
description = "Google (GCP) Service-account"
regex = '''\"type\": \"service_account\"'''

[[rules]]
id = "slack-web-hook"
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8,12}/[a-zA-Z0-9_]{24}'''

[[rules]]
id = "twilio-api-key"
description = "Twilio API Key"
regex = '''SK[0-9a-fA-F]{32}''' # TODO probabaly should be in extractor

[[rules]]
id = "age-secret-key"
description = "Age secret key"
regex = '''AGE-SECRET-KEY-1[QPZRY9X8GF2TVDW0S3JN54KHCE6MUA7L]{58}'''

[[rules]]
id = "adobe-client-secret"
description = "Adobe Client Secret"
regex = '''(p8e-)(?i)[a-z0-9]{32}'''

[[rules]]
id = "alibaba-access-key-id"
description = "Alibaba AccessKey ID"
regex = '''(LTAI)(?i)[a-z0-9]{20}''' # TODO needs a limiter

[[rules]]
id = "clojars-api-token"
description = "Clojars API token"
regex = '''(CLOJARS_)(?i)[a-z0-9]{60}'''

[[rules]]
id = "doppler-api-token"
description = "Doppler API token"
regex = '''(dp\.pt\.)(?i)[a-z0-9]{43}'''

[[rules]]
id = "duffel-api-token"
description = "Duffel API token"
regex = '''(?i)duffel_(test|live)_[a-z0-9_-]{43}'''

[[rules]]
id = "dynatrace-api-token"
description = "Dynatrace API token"
regex = '''dt0c01\.(?i)[a-z0-9]{24}\.[a-z0-9]{64}'''

[[rules]]
id = "easypost-api-token"
description = "EasyPost API token"
regex = '''EZ(A|T)K(?i)[a-z0-9]{54}'''

[[rules]]
id = "easypost-test-api-token"
description = "EasyPost test API token"
regex = '''EZTK(?i)[a-z0-9]{54}'''

[[rules]]
id = "flutterweave-public-key"
description = "Flutterweave public key"
regex = '''FLWPUBK_TEST-(?i)[a-h0-9]{32}-X'''

[[rules]]
id = "flutterweave-secret-key"
description = "Flutterweave secret key"
regex = '''FLWSECK_TEST-(?i)[a-h0-9]{32}-X'''

[[rules]]
id = "flutterweave-enc-key"
description = "Flutterweave encrypted key"
regex = '''FLWSECK_TEST(?i)[a-h0-9]{12}'''

[[rules]]
id = "frameio-api-token"
description = "Frame.io API token"
regex = '''fio-u-(?i)[a-z0-9-_=]{64}'''
#
# [[rules]]
# id = "grafana-api-token"
# description = "Grafana API token"
# regex = '''eyJrIjoi[a-z0-9-_=]{72,92}''' # TODO this is a generic jwt token, should be deleted

[[rules]]
id = "hashicorp-tf-api-token"
description = "Hashicorp Terraform user/org API token"
regex = '''['\"][a-z0-9]{14}\.atlasv1\.[a-z0-9-_=]{60,70}['\"]'''

[[rules]]
id = "linear-api-token"
description = "Linear API token"
regex = '''lin_api_(?i)[a-z0-9]{40}'''

# [[rules]]
# id = "mapbox-api-token"
# description = "Mapbox API token"
# regex = '''(?i)(pk\.[a-z0-9]{60}\.[a-z0-9]{22})'''

[[rules]]
id = "new-relic-user-api-key"
description = "New Relic user API Key"
regex = '''NRAK-[A-Z0-9]{27}'''

[[rules]]
id = "new-relic-browser-api-token"
description = "New Relic ingest browser API token"
regex = '''NRJS-[a-f0-9]{19}'''

[[rules]]
id = "npm-access-token"
description = "npm access token"
mustContain = "npm"
regex = '''(?i)npm_[a-z0-9]{36}'''

[[rules]]
id = "planetscale-password"
description = "Planetscale password"
regex = '''(?i)pscale_pw_[a-z0-9\-_\.]{43}'''

[[rules]]
id = "planetscale-api-token"
description = "Planetscale API token"
regex = '''(?i)pscale_tkn_[a-z0-9\-_\.]{43}'''

[[rules]]
id = "postman-api-token"
description = "Postman API token"
regex = '''(?i)PMAK-[a-f0-9]{24}\-[a-f0-9]{34}'''

[[rules]]
id = "pulumi-api-token"
description = "Pulumi API token"
regex = '''(?i)pul-[a-f0-9]{40}'''

[[rules]]
id = "rubygems-api-token"
description = "Rubygem API token"
regex = '''(?i)rubygems_[a-f0-9]{48}'''

[[rules]]
id = "sendgrid-api-token"
description = "Sendgrid API token"
regex = '''(?i)SG\.[a-z0-9_\-\.]{66}'''

[[rules]]
id = "sendinblue-api-token"
description = "Sendinblue API token"
regex = '''(?i)xkeysib-[a-f0-9]{64}\-[a-z0-9]{16}'''

[[rules]]
id = "shippo-api-token"
description = "Shippo API token"
regex = '''(?i)shippo_(live|test)_[a-f0-9]{40}'''

[[rules]]
id = "typeform-api-token"
description = "Typeform API token"
regex = '''(?i)tfp_[a-z0-9\-_\.=]{59}'''

# this generic rule captures most api keys.
# extractors are used to determine what _kind_ of api keys were captured.
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(?:'|"){0,1}(?:[a-z0-9\-_.]{0,25})(?:key|api|token|secret|client|password|pat)(?:[0-9a-z\-_\s.]{0,20})(?:'|"){0,1}(?:=|>|:=|\|\|:|<=|=>|:)(?:'|\"|\s|=){0,5}([0-9a-z\-_.=]{10,150})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "linkedin-client-id"
description = "Linkedin Client token"
regex = '''(?i)linkedin.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{14})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "linkedin-client-secret"
description = "Linkedin Client Secret"
regex = '''(?i)linkedin.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{16})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "heroku-api-key"
description = "Heroku API Key"
regex = '''[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'''
[[rules.extractors]]
id = "facebook-token"
description = "Facebook token"
regex = '''(?i)facebook.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{32})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "twitch-api-token"
description = "Twitch API token"
regex = '''(?i)twitch.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{30})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "twitter-token"
description = "Twitter token"
regex = '''(?i)twitter.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{35,44})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "adobe-client-id"
description = "Adobe Client ID (Oauth Web)"
regex = '''(?i)adobe.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{32})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "alibaba-secret-key"
description = "Alibaba Secret Key"
regex = '''(?i)alibaba.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{30})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "asana-client-id"
description = "Asana Client ID"
regex = '''(?i)asana.+['|\"|\n|\r|\s|=|:=|:]([0-9]{16})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "asana-client-secret"
description = "Asana Client Secret"
regex = '''(?i)asana.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{32})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "atlassian-api-token"
description = "Atlassian API token"
regex = '''(?i)atlassian.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{24})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "bitbucket-client-id"
description = "Bitbucket client ID"
regex = '''(?i)bitbucket.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{32})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "bitbucket-client-secret"
description = "Bitbucket client secret"
regex = '''(?i)bitbucket.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9_\-]{64})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "beamer-api-token"
description = "Beamer API token"
regex = '''(?i)beamer.+['|\"|\n|\r|\s|=|:=|:](b_[a-z0-9=_\-]{44})['|\"|\n|\r|\s|=|:=|:]'''
secretGroup=1
[[rules.extractors]]
id = "contentful-api-token"
description = "Contentful delivery API token"
regex = '''(?i)contentful.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9\-=_]{43})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "databricks-api-token"
description = "Databricks API token"
regex = '''(?i)dapi[a-h0-9]{32}['|\"|\n|\r|\s]''' # TODO this _could_ be a standalone rule?
[[rules.extractors]]
id = "discord-api-token"
description = "Discord API key"
regex = '''(?i)discord.+['|\"|\n|\r|\s|=|:=|:]([a-h0-9]{64})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "discord-client-id"
description = "Discord client ID"
regex = '''(?i)discord.+['|\"|\n|\r|\s|=|:=|:]([0-9]{18})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "discord-client-secret"
description = "Discord client secret"
regex = '''(?i)discord.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9=_\-]{32})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "dropbox-api-secret"
description = "Dropbox API secret/key"
regex = '''(?i)dropbox.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{15})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "dropbox-short-lived-api-token"
description = "Dropbox short lived API token"
regex = '''(?i)dropbox.+['|\"|\n|\r|\s|=|:=|:](sl\.[a-z0-9\-=_]{135})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "dropbox-long-lived-api-token"
description = "Dropbox long lived API token"
regex = '''(?i)dropbox.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{11}(AAAAAAAAAA)[a-z0-9\-_=]{43})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "fastly-api-token"
description = "Fastly API token"
regex = '''(?i)fastly.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9=_\-]{32})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "finicity-client-secret"
description = "Finicity client secret"
regex = '''(?i)finicity.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{20})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "finicity-api-token"
description = "Finicity API token"
regex = '''(?i)finicity.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{32})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "gocardless-api-token"
description = "GoCardless API token"
regex = '''(?i)gocardless.+['|\"|\n|\r|\s|=|:=|:](live_[a-z0-9-_=]{40})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "hubspot-api-token"
description = "Hubspot API token"
mustContain = "hubspot"
regex = '''(?i)hubspot.+['|\"|\n|\r|\s|=|:=|:]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "intercom-api-token"
description = "Intercom API token"
regex = '''(?i)intercom.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9=_]{60})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "intercom-client-secret"
description = "Intercom client secret/ID"
regex = '''(?i)intercom.+['|\"|\n|\r|\s|=|:=|:]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "ionic-api-token"
description = "Ionic API token"
regex = '''(?i)ion.+['|\"|\n|\r|\s|=|:=|:](ion_[a-z0-9]{42})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "linear-client-secret"
description = "Linear client secret/ID"
regex = '''(?i)linear.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{32})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "lob-api-key"
description = "Lob API Key"
regex = '''(?i)lob.+['|\"|\n|\r|\s|=|:=|:]((?:live|test)_[a-f0-9]{35})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "lob-pub-api-key"
description = "Lob Publishable API Key"
regex = '''(?i)lob.+['|\"|\n|\r|\s|=|:=|:]((?:test|live)_pub_[a-f0-9]{31})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "mailchimp-api-key"
description = "Mailchimp API key"
regex = '''(?i)mailchimp.+['|\"|\n|\r|\s|=|:=|:]([a-f0-9]{32}-us20)['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "mailgun-private-api-token"
description = "Mailgun private API token"
regex = '''(?i)mailgun.+['|\"|\n|\r|\s|=|:=|:](key-[a-f0-9]{32})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "mailgun-pub-key"
description = "Mailgun public validation key"
regex = '''(?i)mailgun.+['|\"|\n|\r|\s|=|:=|:](pubkey-[a-f0-9]{32})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "mailgun-signing-key"
description = "Mailgun webhook signing key"
mustContain = "mailgun"
regex = '''(?i)mailgun.+['|\"|\n|\r|\s|=|:=|:]([a-h0-9]{32}-[a-h0-9]{8}-[a-h0-9]{8})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "messagebird-api-token"
description = "MessageBird API token"
mustContain = "messagebird"
regex = '''(?i)messagebird.+['|\"|\n|\r|\s|=|:=|:]([a-z0-9]{25})['|\"|\n|\r|\s]'''
secretGroup = 1
[[rules.extractors]]
id = "messagebird-client-id"
description = "MessageBird API client ID"
mustContain = "messagebird"
regex = '''(?i)messagebird.+['|\"|\n|\r|\s|=|:=|:]([a-h0-9]{8}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{4}-[a-h0-9]{12})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "new-relic-user-api-id"
description = "New Relic user API ID"
mustContain = "newrelic"
regex = '''(?i)newrelic.+['|\"|\n|\r|\s|=|:=|:]([A-Z0-9]{64})['|\"|\n|\r|\s]'''
secretGroup=1
[[rules.extractors]]
id = "Hashicorp Vault service token"
description = "Hashicorp Vault service token"
regex = '''(?i)vault.+['|\"|\n|\r|\s|=|:=|:](s\.[0-9a-zA-Z]{24})['|\"|\n|\r|\s]'''
secretGroup=1

# global allow list
[allowlist]
description = "global allow lists"
regexes = [
    '''219-09-9999''', 
    '''078-05-1120''', 
    '''(9[0-9]{2}|666)-\d{2}-\d{4}''']
paths = [
    '''gitleaks.toml''',
    '''(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$'''
]
